# Generated by Django 3.2.5 on 2021-07-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anauygulama', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yazılar',
        ),
    ]
