# Generated by Django 3.2.5 on 2021-07-28 17:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='badget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badget', models.TextField(verbose_name='Badget İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='İsDeneyimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('görev', models.CharField(max_length=200, verbose_name='Görev Adı')),
                ('aciklama', ckeditor.fields.RichTextField()),
                ('firmaicon', models.FileField(blank=True, null=True, upload_to='', verbose_name='eklemek isterseniz fotograf seçin ')),
            ],
        ),
        migrations.CreateModel(
            name='KisiselBilgiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.FileField(blank=True, null=True, upload_to='', verbose_name='eklemek isterseniz fotograf seçin ')),
                ('lokasyon', models.TextField(blank=True, null=True, verbose_name='Lokasyon')),
                ('aktiflokasyon', models.TextField(blank=True, null=True, verbose_name='şuanki lokasyonunuz ( Boş Geçilebilir )')),
                ('telefon', models.TextField(blank=True, null=True, verbose_name='telefon numarası giriniz')),
                ('telefon2', models.TextField(blank=True, null=True, verbose_name='ikinci telefon numarası giriniz')),
                ('eposta1', models.TextField(blank=True, null=True, verbose_name='eposta 1 i  giriniz')),
                ('eposta2', models.TextField(blank=True, null=True, verbose_name='eposta 2 i  giriniz')),
            ],
        ),
        migrations.CreateModel(
            name='ozellikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(verbose_name='proje ismi')),
                ('aciklama', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='projeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_ismi', models.TextField(verbose_name='proje ismi')),
                ('platform', models.TextField(verbose_name='Platform')),
                ('acıklama', ckeditor.fields.RichTextField(verbose_name='Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yetenekler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetenek_adi', models.CharField(max_length=200, verbose_name='Yetenek Adı')),
                ('yetenekyuzdesi', models.IntegerField(verbose_name='Yetenek Yüzdesi')),
            ],
        ),
    ]
