# Generated by Django 3.2.5 on 2021-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_profilfotografı'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='aktiflokasyon',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='eposta1',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='eposta2',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='fotograf',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='telefon2',
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='eposta',
            field=models.TextField(blank=True, null=True, verbose_name='E-posta yı giriniz'),
        ),
    ]
